### ISSUE TITLE
Add automatic nightly builds

### ISSUE THREAD

**Issue by ethanfrey** [confio/ts-relayer#143] opened 2021-03-30 12:12 UTC
CI script to push something every night, for those who want the most recent bug fixes without building from source. (option: on every merge to master - call it `tip` or 'edge'?)

Is this another tag? Another npm package?

In any case someone should have to opt-in to use it over stable releases

**Comment by bartmacbartek** [comment] 2021-03-31 07:27
I say let's do `@next` tag that would represent the upcoming version, or in other words, the current (latest) code that is available on the `main` branch.

**Comment by willclarktech** [comment] 2021-03-31 09:08
`@next` sounds sensible if we want to distribute via npm, but if it's pushed on every merge to master that sounds like a lot of prerelease versions. (Not necessarily a bad thing, but might look strange.)

**Comment by ethanfrey** [comment] 2021-03-31 09:30
If I `yarn add @confio/ts-relayer@next` and then a new version is pushed, and I run `yarn install` again, will it download the new one? Or see it already has `@next` locally and do nothing?

This could cause very different behavior from CI (fresh install) to dev machines (cached)

**Comment by willclarktech** [comment] 2021-03-31 09:41
From https://classic.yarnpkg.com/en/docs/cli/install:
> If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass --frozen-lockfile flag.

**Comment by ethanfrey** [comment] 2021-03-31 11:12
I don't know how this all works, I just want to make sure someone has thought through this main workflow

**Comment by bartmacbartek** [comment] 2021-04-01 03:04
I gave it some thought and did tests. **The goal is to make the code on the `main` branch available for testing.**

I suggested the `next` tag but I'm not sure about this anymore. Tag exists with a specific version, and since we don't know the exact upcoming version number we would run into misalignment (for example `0.1.2-rc@next` could correspond to future version `0.2.0`).

---

Instead, I would like to publish version `0.0.0-main-${sha-1}` and tag it with `main` on every merge to the `main` branch.

It means, that it would be possible to install relayer from the `main` branch via:
```bash
npm i -g @confio/relayer@main
```
or run directly via `npx`:
```bash
npx -p @confio/relayer@main ibc-setup --help
```

---

@ethanfrey 
>When they run that command again, will they get the next version or the local cache? If it is the local cache, then this is a problem

I can confirm that whenever a new `main` tag is published (PR is merged to `main`) then:
```bash
npm i -g @confio/relayer@main # overrides the previous main with a new one
npx -p @confio/relayer@main ibc-setup --help # uses latest code on main
```

@willclarktech 
>if it's pushed on every merge to master that sounds like a lot of prerelease versions. (Not necessarily a bad thing, but might look strange.)

I don't think it's an issue either. Also, if we feel it looks strange in the future, we can easily opt-out of it by unpublishing (you can unpublish but not override) all the `0.0.0-main-${sha-1}` versions so they not appear on the npmjs.com.
```bash
npm view @confio/relayer versions --json \
    | jq -r '.[] | select(startswith("0.0.0-main-"))' \
    | while read v; do npm unpublish @confio/relayer@$v; done
```

Please have a look at https://github.com/confio/ts-relayer/pull/147, what do you think?

**Comment by ethanfrey** [comment] 2021-04-01 07:12
Thanks for testing this. It seems like a good solution.

I just tried `npx -p @confio/relayer@main ibc-setup --help` but it seems it is not published (not listed on https://www.npmjs.com/package/@confio/relayer either).

The solutions sounds good. Let's publish one and if there are issues, we can update it.

**Comment by bartmacbartek** [comment] 2021-04-01 07:41
>I just tried npx -p @confio/relayer@main ibc-setup --help but it seems it is not published (not listed on https://www.npmjs.com/package/@confio/relayer either).

The commands I included are dry. I tested this but with a fake package, so atm `@main` is not published.

You still can do:
```
npx -p @confio/relayer ibc-setup --help
```

**Closed** 2021-04-01 14:48 UTC
